CONFIG_ZMK_HID=y

# BLE 发射功率
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# USB 有线模式
CONFIG_ZMK_USB=y

# 组合键
CONFIG_ZMK_COMBO_MAX_PRESSED_COMBOS=10
CONFIG_ZMK_COMBO_MAX_COMBOS_PER_KEY=10

# 蓝牙免密配对
CONFIG_ZMK_BLE_PASSKEY_ENTRY=n

# 省电
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

# 消抖
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5
